CREATE DATABASE DIARIODELCAZADOR

CREATE TABLE foto_perfil
(
	CodFot INT NOT NULL,
	NomFot VARCHAR(45) NOT NULL
	PRIMARY KEY (CodFot)
);

CREATE TABLE usuario
(
	CodUsu INT NOT NULL IDENTITY,
	NomUsu VARCHAR(45) NOT NULL,
	Ape1Usu VARCHAR(45) NOT NULL,
	Ape2Usu VARCHAR(45) NULL,
	EmailUsu VARCHAR(45) NOT NULL UNIQUE CHECK (EmailUsu LIKE '%@%.%'),
	NickUsu VARCHAR(45) NOT NULL UNIQUE,
	ContrUsu VARCHAR(45) NOT NULL,
	FechNacUsu DATE NOT NULL,
	AdminUsu BIT NOT NULL DEFAULT 0,
	CodFot INT NULL,
	PRIMARY KEY (CodUsu),
	FOREIGN KEY (CodFot) REFERENCES foto_perfil(CodFot)
							ON UPDATE NO ACTION
							ON DELETE SET NULL
);

CREATE TABLE zona
(
	CodZona INT NOT NULL,
	NomZona VARCHAR(45) NOT NULL,
	DescZona VARCHAR(1000) NOT NULL
	PRIMARY KEY(CodZona)
);

CREATE TABLE enemigo
(
	CodEne INT NOT NULL IDENTITY,
	NomEne VARCHAR(45) NOT NULL,
	DescEne VARCHAR(1000) NOT NULL,
	BossEne BIT NOT NULL DEFAULT 0,
	CodZona INT NOT NULL,
	PRIMARY KEY(CodEne),
	FOREIGN KEY (CodZona) REFERENCES zona(CodZona)
							ON UPDATE NO ACTION
							ON DELETE CASCADE
);